server:
  port: 8081

# 微服务配置
spring:
  application:
    name: system-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.100:3306/xcplus_system?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: mysql
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml

#swagger:
#  title: "学成在线内容管理系统"
#  description: "内容系统管理系统对课程相关信息继续管理"
#  base-package: com.xuecheng.content
#  enabled: true
#  version: 1.0.0

